services:
    fd.form.help_type_extension:
        class: Fd\OfertaEducativaBundle\Form\Extension\HelpTypeExtension
        tags: 
            - { name: form.type_extension, alias: form }
    ofertaeducativa.carrera.manager:
        class: Fd\OfertaEducativaBundle\Model\CarreraManager
        arguments: 
            entity_manager: "@doctrine.orm.entity_manager"
    ofertaeducativa.ofertaeducativa.manager:
        class: Fd\OfertaEducativaBundle\Model\OfertaEducativaManager
        arguments: 
            entity_manager: "@doctrine.orm.entity_manager"