ActoPublicoBundle:
    resource: "@ActoPublicoBundle/Resources/config/routing.yml"

BackendBundle:
    resource: "@BackendBundle/Resources/config/routing.yml"

EdificioBundle:
    resource: "@EdificioBundle/Resources/config/routing.yml"

EstablecimientoBundle:
    resource: "@EstablecimientoBundle/Resources/config/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

portada:
    pattern: /
    defaults: { _controller: EstablecimientoBundle:Default:portada }

OfertaEducativaBundle:
    resource: "@OfertaEducativaBundle/Resources/config/routing.yml"

sonata:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

TablaBundle:
    resource: "@TablaBundle/Resources/config/routing.yml"

UsuarioBundle:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario