acto_publico:
    resource: "@ActoPublicoBundle/Controller/"
    type:     annotation
    prefix:   /acto_publico

BackendBundleBarrio:
    resource: "@BackendBundle/Controller/BarrioController.php"
    type:     annotation
    prefix:   /backend

BackendBundleCargoAutoridad:
    resource: "@BackendBundle/Controller/CargoAutoridadController.php"
    prefix:   /backend
    type:     annotation

BackendBundleCgp:
    resource: "@BackendBundle/Controller/CgpController.php"
    type:     annotation
    prefix:   /backend    

BackendBundleCohorte:
    resource: "@BackendBundle/Controller/CohorteController.php"
    type:     annotation
    prefix:   /backend    

BackendBundleComuna:
    resource: "@BackendBundle/Controller/ComunaController.php"
    type:     annotation

BackendBundleDefault:
    resource: "@BackendBundle/Controller/DefaultController.php"
    prefix:   /backend
    type:     annotation

BackendBundleDistritoEscolar:
    resource: "@BackendBundle/Controller/DistritoEscolarController.php"
    type:     annotation
    prefix:   /backend    

BackendBundleDomicilio:
    resource: "@BackendBundle/Controller/DomicilioController.php"
    type:     annotation
    prefix:   /backend    

BackendBundleDomicilioLocalizacion:
    resource: "@BackendBundle/Controller/DomicilioLocalizacionController.php"
    type:     annotation
    prefix:   /backend    

BackendBundleEdificio:
    resource: "@BackendBundle/Controller/EdificioController.php"
    type:     annotation    
    prefix:   /backend

BackendBundleEstablecimiento:
    resource: "@BackendBundle/Controller/EstablecimientoController.php"
    type:     annotation    
    prefix:   /backend    

BackendBundleEstablecimientoEdificio:
    resource: "@BackendBundle/Controller/EstablecimientoEdificioController.php"
    type:     annotation
    prefix:   /backend    

BackendBundleGrupoEtario:
    resource: "@BackendBundle/Controller/GrupoEtarioController.php"
    type:     annotation
    prefix:   /backend    

BackendBundleInicialX:
    resource: "@BackendBundle/Controller/InicialXController.php"
    type:     annotation
    prefix:   /backend    

BackendBundleLocalizacion:
    resource: "@BackendBundle/Controller/LocalizacionController.php"
    type:     annotation
    prefix:   /backend    

BackendBundleModalidad:
    resource: "@BackendBundle/Controller/ModalidadController.php"
    type:     annotation
    prefix:   /backend    

BackendBundleNivel:
    resource: "@BackendBundle/Controller/NivelController.php"
    type:     annotation
    prefix:   /backend    

BackendBundlePortada:
    resource: "@BackendBundle/Controller/PortadaController.php"
    type:     annotation
    prefix:   /backend

BackendBundleProvincia:
    resource: "@BackendBundle/Controller/ProvinciaController.php"
    type:     annotation
    prefix:   /backend    

BackendBundlePais:
    resource: "@BackendBundle/Controller/PaisController.php"
    type:     annotation
    prefix:   /backend    

BackendBundleRecurso:
    resource: "@BackendBundle/Controller/RecursoController.php"
    type:     annotation
    prefix:   /backend    

BackendBundleSector:
    resource: "@BackendBundle/Controller/SectorController.php"
    type:     annotation
    prefix:   /backend    

BackendBundleTipoNorma:
    resource: "@BackendBundle/Controller/TipoNormaController.php"
    type:     annotation
    prefix:   /backend    

BackendBundleTitulo:
    resource: "@BackendBundle/Controller/TituloController.php"
    type:     annotation
    prefix:   /backend    

BackendBundleUnidadEducativa:
    resource: "@BackendBundle/Controller/UnidadEducativaController.php"
    type:     annotation
    options:
        expose: true

BackendBundleVecino:
    resource: "@BackendBundle/Controller/VecinoController.php"
    type:     annotation

BackendBundle:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /backend   
    options:
        expose: true    

EdificioBundle:
    resource: "@EdificioBundle/Controller/DefaultController.php"
    type:     annotation

EstablecimientoDefaultBundle:
    resource: "@EstablecimientoBundle/Controller/"
    type:     annotation
    options:
        expose: true    

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

## DEPRECATED
#
#EstablecimientoDefaultBundle:
#    resource: "@EstablecimientoBundle/Controller/DefaultController.php"
#    type:     annotation
#
#EstablecimientoBundle:
#    resource: "@EstablecimientoBundle/Controller/EstablecimientoController.php"
#    type:     annotation
#
#EstablecimientoUnidadEducativaBundle:
#    resource: "@EstablecimientoBundle/Controller/UnidadEducativaController.php"
#    type:     annotation
#
#EstablecimientoBundlePrimario:
#    resource: "@EstablecimientoBundle/Controller/PrimarioController.php"
#    type:     annotation
#
#EstablecimientoBundleInicial:
#    resource: "@EstablecimientoBundle/Controller/InicialController.php"
#    type:     annotation
#
#EstablecimientoBundleMedio:
#    resource: "@EstablecimientoBundle/Controller/MedioController.php"
#    type:     annotation
portada:
    pattern: /
    defaults: { _controller: EstablecimientoBundle:Default:portada }


TablaBundle:
    resource: "@TablaBundle/Controller/DefaultController.php"
    type:     annotation

OfertaEducativaBundle:
    resource: "@OfertaEducativaBundle/Controller/"
    type:     annotation
    prefix:   /oferta
    options:
        expose: true

sonata:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

UsuarioBundle:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario