usuario_identificacion:
    pattern: /identificacion/{id}
    defaults: { _controller: UsuarioBundle:Default:identificacion }

usuario_login:
    pattern: /login
    defaults: { _controller: UsuarioBundle:Default:login }
    
usuario_login_check:
    pattern: /login_check
    
usuario_logout:
    pattern: /logout

usuario_registro:
    pattern: /registro
    defaults: { _controller: UsuarioBundle:Default:registro }

usuario_perfil:
    pattern: /perfil
    defaults: { _controller: UsuarioBundle:Default:perfil }

usuario_index:
    pattern: /index
    defaults: { _controller: UsuarioBundle:Default:index }

usuario_nuevo:
    pattern: /nuevo
    defaults: { _controller: UsuarioBundle:Default:nuevo }

usuario_crear:
    pattern: /crear
    defaults: { _controller: UsuarioBundle:Default:crear }

usuario_editar:
    pattern: /editar/{id}
    defaults: { _controller: UsuarioBundle:Default:editar }

usuario_eliminar:
    pattern: /eliminar/{id}
    defaults: { _controller: UsuarioBundle:Default:eliminar }

usuario_actualizar:
    pattern: /actualizar/{id}
    defaults: { _controller: UsuarioBundle:Default:actualizar }

usuario_cambio_password:
    pattern: /cambio_password/{id}
    defaults: { _controller: UsuarioBundle:Default:cambio_password }

usuario_cambiar_password:
    pattern: /cambiar_password/{id}
    defaults: { _controller: UsuarioBundle:Default:cambiar_password }