services:
    sonata.fd.establecimiento.admin.establecimiento:
        class: Fd\EstablecimientoBundle\Admin\EstablecimientoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Establecimiento, label: Establecimiento }
        arguments: [ null, Fd\EstablecimientoBundle\Entity\Establecimiento , EstablecimientoBundle:Admin ]